### ISSUE TITLE
svg 是如何实现的？

### ISSUE THREAD

**Issue by kuizuo** [inannan423/inannan423.github.io#1]
想请教下这类svg是如何自定义实现的，尤其是文字的部分有点意思
<img width="659" alt="image" src="https://user-images.githubusercontent.com/61005888/181231164-8418664c-9675-43bd-a619-c3e81f58ce95.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/61005888/181231359-715a72c9-8ada-4b36-acfc-70d14c334909.png">

**Comment by inannan423** [comment]
这个是使用即时设计做的哈哈，用代码写不出，这个工具可以导出svg，这里有这个字体资源的链接：https://js.design/resourceDetails?id=62b13ce8d2bf5447124af378

**Comment by kuizuo** [comment]
谢谢，你的主页设计看起来很酷，可以的话互换下友链。

https://kuizuo.cn/friends/

**Comment by inannan423** [comment]
> 谢谢，你的主页设计看起来很酷，可以的话互换下友链。
> 
> https://kuizuo.cn/friends/

好的，但是这个申请友链失效啦，![image.png](https://jetzihan-img.oss-cn-beijing.aliyuncs.com/blog/20220728084620.png)，我参考了你的导航代码，你在致谢那一栏。

**Comment by kuizuo** [comment]
好的，有时间可以技术探讨，祝你学习顺利，永无bug。😃
